export const NAVIGATION_LOGIN = 'NAVIGATION_LOGIN';
export const NAVIGATION_MAIN_APP = 'NAVIGATION_MAIN_APP';
export const NAVIGATION_BOTTOM_TAB = 'NAVIGATION_BOTTOM_TAB';
export const NAVIGATION_TAB_HOME = 'NAVIGATION_TAB_HOME';
export const ROUTE_LOGIN = 'ROUTE_LOGIN';
export const ROUTE_HOME = 'ROUTE_HOME';